name: Go Report Card

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Go Report Card

    steps:
      - name: Refresh Go Report Card
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0
